### PR TITLE
Update metadata shell no to support GNOME 40

### PR DESCRIPTION
**Pull request by prateekmedia**
As approved by https://www.google.com/amp/s/www.omgubuntu.co.uk/2020/09/gnome-40-version-number-change/amp gnome will no longer follow 3.40 and 3.42 but will follow 40 and 41 and so on...

### CODE REVIEW

**Comment by prateekmedia** [comment]
Gnome 40 is out now.

**Review by biji — COMMENTED** [review]
haven't check yet, is it `40` or `40.0`?

**Comment by prateekmedia** [comment]
> have check yet, is it `40` or `40.0`?

It is 40, I have also done it in my extension.

The problem with 40.0 is that it will not support 40.beta or others.

**Comment by prateekmedia** [comment]
Oh, I have fixed a bug where the extension cannot be detected by the shell due to comma at the end of the shell no.'s and also I bumped the version no to 21.

**Comment by prateekmedia** [comment]
40.0 in the new version scheme is equivalent to 3.38.0 in the old one, i.e. this will stop working as soon as 40.1 is released in a couple of weeks.

**Pull request merged**
